import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import PageTemplate from '../components/PageTemplate';
import { ROTATION_BADGE_REQUIREMENTS, RotationBadgeId, PROGRAMME_LABELS } from '../types/creatorJourney';
import './WhatYouBuildPage.css';

type Stage = 1 | 2 | 3 | 4;

const SEVEN_ASSETS = [
  { id:'portfolio', icon:'◈', name:'Product portfolio',   claim:'Not a catalogue. A body of work with a provenance trail.', detail:'Each product connected to the knowledge that produced it, the process that made it, the community that validated it. A customer who can trace your work to its source is not buying a product -- they are buying into a practice they can follow. That trail converts a one-time buyer into a returning customer.', mechanism:'Cyberstore listings with counter-archive tokens', mechanismUrl:'/shop', colour:'#d4a853' },
  { id:'position',  icon:'◆', name:'Market position',     claim:'Not a niche. A specific answer to a specific need.', detail:'The ROCE data reveals which creative practices are most commercially efficient for you specifically. The creator who discovers their ambient music earns 31 pounds per hour while their drum kits earn 4 pounds per hour does not need to compete on drum kits. That is a strategic market position derived from personal data, not generic market research.', mechanism:'ROCE calculator in the Impact Lab', mechanismUrl:'/creator/impact-lab', colour:'#60a5fa' },
  { id:'brand',     icon:'✦', name:'Brand',               claim:'Not a logo. A consistent creative voice documented across domains.', detail:'The creator who has articles, music tracks, broadcasts, and a Cyberstore portfolio -- all connected through the Knowledge Commons archive -- has a brand that a designer cannot manufacture. It is evidenced by outputs. It compounds over time. The archive is the brand record.', mechanism:'Knowledge Commons archive and provenance tokens', mechanismUrl:'/heritage', colour:'#a78bfa' },
  { id:'customers', icon:'◎', name:'Customer depth',      claim:'Not followers. Subscribers who belong to you, not the platform.', detail:'The subscriber consent system means your audience is portable. Every customer who subscribes is giving you the relationship, not the platform. When you leave, they can leave with you. Fifty customers who have bought multiple times are worth more than fifty thousand followers who glanced once. Customer depth, not market reach.', mechanism:'Subscriber consent system and portable audience', mechanismUrl:'/how-it-works', colour:'#4ade80' },
  { id:'literacy',  icon:'£', name:'Financial literacy',  claim:'Not a budgeting course. Your own financial data, live.', detail:'The 55/25/20 split is not abstract when you can trace your earnings to the hours you spent. ROCE is not a concept when your Impact Lab shows the difference between two practices. The Pardner is not an acronym when your ILP shows exactly which quarter it funded. Financial literacy through lived experience of your own numbers.', mechanism:'Impact Lab, ROCE metric, ILP Pardner context', mechanismUrl:'/creator/impact-lab', colour:'#d4a853' },
  { id:'network',   icon:'◎', name:'Business network',    claim:'Not connections. Relationships built through shared work.', detail:'Programme rotation creates genuine working relationships across 13 communities. The Makers Collective creates shared investment in collective infrastructure. The Stewards Council puts creators in the room where decisions are made. These relationships are generated by work, not by networking events.', mechanism:'Programme rotation, Makers Collective, Stewards Council, two Houses', mechanismUrl:'/houses', colour:'#f472b6' },
  { id:'capital',   icon:'◈', name:'Working capital',     claim:'Not a loan. Community investment in your development stage.', detail:'The Pardner is structured as a business floor payment because that is what it is -- the community betting on a creator building toward commercial viability. The ILP shows the community what the investment is funding. For a bank or grant body, the Pardner history in your ILP reads as social proof: the community invested in you.', mechanism:'Cultivation Pardner, ILP, quarterly transparency report', mechanismUrl:'/governance', colour:'#34d399' },
];

const STAGES = [
  { stage:1 as Stage, label:'Single programme',           desc:'One income stream. ROCE in one domain.', detail:'Revenue from one creative practice. Limited audience. High dependence on that practice\'s commercial conditions. The foundation -- real, valuable, but not yet compound.', earningsNote:'Earnings: single stream' },
  { stage:2 as Stage, label:'Multiple programmes active', desc:'ROCE comparison. Audience overlap beginning.', detail:'Multiple income streams. The ROCE data starts revealing which practice is most efficient. The creator who finds their Joystick audience also buys their music. Each programme strengthens the others.', earningsNote:'Earnings: multiple streams, comparative data' },
  { stage:3 as Stage, label:'Rotation badges earned',     desc:'Compound effect visible. Customer depth deepening.', detail:'Not just multiple streams -- streams that reinforce each other. The broadcaster audience knows the maker. The editorial audience knows the broadcaster. The customer who has followed you across three programmes is invested in your practice.', earningsNote:'Earnings: compound, cross-programme audience' },
  { stage:4 as Stage, label:'Full participation',         desc:'Seven assets complete. ILP exportable.', detail:'The seven assets fully developed. The ILP exportable as a business plan. The customer base portable. The brand legible across domains. The financial literacy operational. The business network active. This is what the platform was built to produce.', earningsNote:'Earnings: full compound, portable, credentialled' },
];

const BACKBONE = [
  { icon:'🧵', title:'The Makers Collective', desc:'Shared equipment becomes possible when enough makers are invested. The Silk Stilettos creator who also completed STEMgeneers brings textile and technical expertise together. The combination creates capabilities the collective could not have from single-programme participants.', link:'/governance' },
  { icon:'◈',     title:'The Mentor tier',       desc:'The programme rotation includes a Mentor level at each programme. A fully-rotated creator who reaches Mentor tier in two or three programmes has become part of the delivery infrastructure. They are training the next cohort. The platform replicates itself.', link:'/programmes' },
  { icon:'🏛', title:'The Stewards Council',  desc:'Fully-rotated creators are the natural candidates for the Stewards Council. They understand the platform across domains. They have skin in the game across multiple income streams. They are invested in making the reserve and the Pardner work.', link:'/governance' },
  { icon:'◆',     title:'The proof of concept',  desc:'A creator with a full ILP, multiple rotation badges, ROCE data across domains, and a Cyberstore portfolio is the embodiment of what the Equiano Principle looks like when it works. They are what the platform points to when funders ask: does this work?', link:'/manifesto' },
];

const WhatYouBuildPage: React.FC = () => {
  const [activeStage, setActiveStage] = useState<Stage>(1);
  const [expandedAsset, setExpandedAsset] = useState<string | null>(null);
  const stage = STAGES.find(s => s.stage === activeStage)!;

  return (
    <PageTemplate pageTitle="What You Build" pageStrapline="Participation in this platform is equivalent to building a small business. Not aspiration. Architecture." pageType="standard">
      <div className="wyb-content">

        <section className="wyb-claim">
          <p className="wyb-claim-lead">Every other platform promises reach.</p>
          <p className="wyb-claim-body">Streams. Views. Followers. Engagement rate. These metrics tell the creator how useful they are to the platform\'s growth. They do not tell the creator how much their work is worth per hour. They do not build anything the creator can take with them when they leave.</p>
          <p className="wyb-claim-body">Wembley Wonders is built around a different question: what does the creator end up with?</p>
          <p className="wyb-claim-emphasis">The answer is seven specific assets, produced by seven specific platform mechanisms, that together constitute a small business.</p>
          <div className="wyb-claim-links">
            <Link to="/how-it-works" className="wyb-claim-link">How the 55/25/20 model works</Link>
            <Link to="/manifesto" className="wyb-claim-link">The Manifesto</Link>
          </div>
        </section>

        <section className="wyb-assets">
          <h2>The seven assets</h2>
          <p className="wyb-section-intro">Each asset is produced by a specific platform mechanism. Not promised. Built.</p>
          <div className="wyb-assets-grid">
            {SEVEN_ASSETS.map(asset => (
              <div key={asset.id} className={'wyb-asset-card' + (expandedAsset === asset.id ? ' wyb-asset-card--open' : '')} style={{'--asset-colour': asset.colour} as React.CSSProperties}>
                <button className="wyb-asset-header" onClick={() => setExpandedAsset(expandedAsset === asset.id ? null : asset.id)}>
                  <span className="wyb-asset-icon">{asset.icon}</span>
                  <div className="wyb-asset-titles">
                    <span className="wyb-asset-name">{asset.name}</span>
                    <span className="wyb-asset-claim">{asset.claim}</span>
                  </div>
                  <span className="wyb-asset-chevron">{expandedAsset === asset.id ? '↑' : '↓'}</span>
                </button>
                {expandedAsset === asset.id && (
                  <div className="wyb-asset-body">
                    <p>{asset.detail}</p>
                    <Link to={asset.mechanismUrl} className="wyb-asset-mechanism">Platform mechanism: {asset.mechanism} →</Link>
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        <section className="wyb-compound">
          <h2>The compound effect</h2>
          <p className="wyb-section-intro">Single-programme participation produces real value. Full participation produces something qualitatively different. The combination is not the sum of the parts.</p>
          <div className="wyb-stages-nav">
            {STAGES.map(s => (
              <button key={s.stage} className={'wyb-stage-btn' + (activeStage === s.stage ? ' active' : '')} onClick={() => setActiveStage(s.stage)}>
                <span className="wyb-stage-num">Stage {s.stage}</span>
                <span className="wyb-stage-label">{s.label}</span>
              </button>
            ))}
          </div>
          <div className="wyb-stage-panel">
            <div className="wyb-stage-content">
              <h3>{stage.label}</h3>
              <p className="wyb-stage-desc">{stage.desc}</p>
              <p className="wyb-stage-detail">{stage.detail}</p>
              <div className="wyb-stage-earnings">
                <span className="wyb-stage-earnings-label">{stage.earningsNote}</span>
                {activeStage < 4 && <button className="wyb-stage-next" onClick={() => setActiveStage((activeStage + 1) as Stage)}>What comes next →</button>}
                {activeStage === 4 && <Link to="/creator/impact-lab" className="wyb-stage-next">See your Impact Lab →</Link>}
              </div>
            </div>
          </div>
          <div className="wyb-compound-link">
            <Link to="/creator/impact-lab" className="wyb-link-card">
              <span className="wyb-link-icon">◈</span>
              <div><strong>Impact Lab</strong><span>Your ROCE, earnings, and compound trajectory -- live</span></div>
            </Link>
          </div>
        </section>

        <section className="wyb-ilp">
          <h2>The Individual Learning Plan</h2>
          <p className="wyb-section-intro">This is not a learning plan with commercial applications. It is a business plan with learning as the development mechanism.</p>
          <div className="wyb-ilp-content">
            <div className="wyb-ilp-text">
              <p>The ILP is maintained by Maya. It is owned by you. It connects your badge sequence into a coherent professional narrative. It exports as a document you can take anywhere.</p>
              <p>When you bring your ILP to a bank, it reads as a business plan with a market position, a product portfolio, and financial data. When you bring it to a grant body, it shows documented outputs, community investment, and a sustainability model.</p>
              <p className="wyb-ilp-emphasis">This is the credential the boardroom recognises. Not the badge in isolation. The ILP that connects the badges into a coherent professional narrative.</p>
            </div>
            <div className="wyb-ilp-contents">
              <h3>What the ILP contains</h3>
              <ul>
                <li>Practice type and market position</li>
                <li>Programme rotation plan and rationale</li>
                <li>Milestone sequence with achieved and projected dates</li>
                <li>ROCE trajectory across all active practices</li>
                <li>Badges earned and rotation badges unlocked</li>
                <li>Pardner context if relevant</li>
                <li>12-month vision in your own voice</li>
                <li>Export-ready PDF for external use</li>
              </ul>
              <Link to="/creators-journal" className="wyb-ilp-link">View your ILP in the Creator Journal →</Link>
            </div>
          </div>
        </section>

        <section className="wyb-backbone">
          <h2>What full participation produces for the community</h2>
          <p className="wyb-section-intro">Fully-rotated creators do not just earn more. They become the infrastructure that makes the platform work for everyone who comes after them.</p>
          <div className="wyb-backbone-grid">
            {BACKBONE.map(item => (
              <Link key={item.title} to={item.link} className="wyb-backbone-card">
                <span className="wyb-backbone-icon">{item.icon}</span>
                <h3>{item.title}</h3>
                <p>{item.desc}</p>
              </Link>
            ))}
          </div>
        </section>

        <section className="wyb-rotation">
          <h2>The rotation badges</h2>
          <p className="wyb-section-intro">Eight combinations. Each one creates compound value no single programme can produce.</p>
          <div className="wyb-rotation-grid">
            {(Object.entries(ROTATION_BADGE_REQUIREMENTS) as [RotationBadgeId, typeof ROTATION_BADGE_REQUIREMENTS[RotationBadgeId]][]).map(([id, req]) => (
              <div key={id} className="wyb-rotation-card">
                <h3>{req.label}</h3>
                <p className="wyb-rotation-desc">{req.description}</p>
                <div className="wyb-rotation-programmes">
                  {req.programmes.map(p => <span key={p} className="wyb-rotation-prog">{PROGRAMME_LABELS[p]}</span>)}
                </div>
              </div>
            ))}
          </div>
          <Link to="/creators-journal" className="wyb-rotation-link">See your rotation progress in the Creator Journal →</Link>
        </section>

        <section className="wyb-start">
          <div className="wyb-start-inner">
            <h2>Tell me what you already know.</h2>
            <p>Maya will build your ILP from the first thing you tell her about your existing practice. The rotation plan follows from that.</p>
            <div className="wyb-start-actions">
              <Link to="/get-started" className="wyb-start-primary">Start building</Link>
              <Link to="/programmes" className="wyb-start-secondary">See the 13 programmes</Link>
              <Link to="/creator/impact-lab" className="wyb-start-secondary">Impact Lab</Link>
            </div>
            <p className="wyb-start-note">Already a creator? <Link to="/creators-journal">View your ILP →</Link></p>
          </div>
        </section>

      </div>
    </PageTemplate>
  );
};

export default WhatYouBuildPage;
