/*
 * G-TECH COMMUNITY PLATFORM IP PROTECTION
 * Copyright (c) 2024-2026 Wembley Wonders CIC
 * Company No. 12960817
 * All rights reserved.
 *
 * HERITAGE PAGE — The Knowledge Commons
 * Public entry point. No login required to explore.
 * Login required to contribute.
 *
 * Aesthetic direction: Editorial archive — the quality of a well-curated
 * independent press, the authority of a counter-institution.
 * Warm black ground. Aged paper accents. Gold for significance.
 * Typography: display serif for headings, refined sans for body.
 * Feels assembled by people who care, not generated by a system.
 */

import React, { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import StoryForm from '../../features/heritage/StoryForm';
import MayaCrisisIntegration from '../../integrations/MayaCrisisIntegration';
import {
  BLACK_BRITISH_EXCELLENCE,
  LONDON_ROUTES,
  TIMELINE_GAME_EVENTS,
  SOUND_JOURNEYS,
  getProfilesByDiscipline,
  getProfilesByEra,
  getLocalHeroes,
  getPioneersByScore,
  type ExcellenceProfile,
  type Era,
  type Discipline,
} from '../../systems/excellence/BlackBritishExcellence';
import './heritage.css';

// ============================================
// TYPES
// ============================================

type BrowseMode = 'welcome' | 'thread' | 'place' | 'era' | 'question' | 'contribute';
type ActiveThread = string | null;

interface Thread {
  id: string;
  title: string;
  question: string;
  profileIds: string[];
  synopsis: string;
  duration: string;
  tags: string[];
}

// ============================================
// THREADS DATA
// Curated narrative paths through the knowledge base
// ============================================

const THREADS: Thread[] = [
  {
    id: 'same-rule-different-arenas',
    title: 'The Same Rule, Different Arenas',
    question: 'Why does racial exclusion keep reappearing in different industries, with different justifications, across 130 years?',
    profileIds: ['arthur-wharton', 'len-johnson', 'lewis-hamilton', 'jazzie-b', 'kanya-king'],
    synopsis: 'Arthur Wharton was excluded from football\'s memory. Len Johnson was excluded from the British title by written rule. Lewis Hamilton was alone on the F1 grid for 15 years. Jazzie B built his own industry because the existing one wasn\'t built for him. Kanya King remortgaged her home because no one would fund the ceremony. One argument. Five arenas. 130 years.',
    duration: '12 min read',
    tags: ['sport', 'music', 'structural racism', 'self-determination']
  },
  {
    id: 'who-owns-the-culture',
    title: 'Who Owns the Culture?',
    question: 'When Black cultural forms become globally valuable, who holds the rights — and how did that happen?',
    profileIds: ['jazzie-b', 'kanya-king', 'michaela-coel'],
    synopsis: 'Jazzie B built Soul II Soul\'s community infrastructure before signing anything. Kanya King created the ceremony the industry refused to create. Michaela Coel left a million dollars on the table to keep her copyright. Three different responses to the same extraction architecture — and what each one teaches about ownership.',
    duration: '10 min read',
    tags: ['ownership', 'copyright', 'music business', 'creative economy']
  },
  {
    id: 'landscape-under-your-feet',
    title: 'The Landscape Under Your Feet',
    question: 'What does the ground of Wembley actually remember — and what has it been made to forget?',
    profileIds: ['arthur-wharton', 'claudia-jones', 'daley-thompson'],
    synopsis: '1924: The British Empire Exhibition is held at Wembley. The stadium is built for it. The tube station upgraded. 1948: The Windrush docks at Tilbury. The children and grandchildren of the Empire\'s subjects begin living on the land of the exhibition that celebrated their subjection. 1959: Claudia Jones creates the Carnival as a response to race riots. The ground remembers everything.',
    duration: '15 min read',
    tags: ['Wembley', 'Empire', 'Windrush', 'geography', 'local history']
  },
  {
    id: 'from-kingston-to-the-grid',
    title: 'From Kingston to the Grid',
    question: 'How did a musical tradition that started in Jamaica in the 1950s become the DNA of British popular music?',
    profileIds: ['jazzie-b', 'kanya-king'],
    synopsis: 'Ska to rocksteady to reggae to lovers rock — the first specifically Black British pop genre, invented in South London. To sound systems to Soul II Soul\'s warehouses to jungle to UK garage to grime. Seventy years of one continuous conversation, carried along tube lines, through community halls, across pirate radio frequencies.',
    duration: '8 min read',
    tags: ['music', 'sound lineage', 'Caribbean', 'London', 'tube map']
  },
  {
    id: 'distance-embassy-community',
    title: 'The Distance Between the Embassy and the Community',
    question: 'Your nation has formal institutional representation in London. How far is it from where you actually live?',
    profileIds: ['kanya-king', 'claudia-jones'],
    synopsis: 'The Jamaican High Commission is in Belgrave Square. The Ghanaian High Commission is in Belgrave Square. The Barbadian High Commission is in Kensington. The communities these missions nominally represent are in Wembley, Brixton, Hackney, Handsworth. This thread maps the distance — geographic and institutional — between formal representation and lived community.',
    duration: '10 min read',
    tags: ['embassies', 'Commonwealth', 'institutional geography', 'diaspora']
  },
  {
    id: 'joy-as-politics',
    title: 'Joy as Politics',
    question: 'When is celebration an act of resistance — and what happens when it gets absorbed into the mainstream?',
    profileIds: ['claudia-jones', 'daley-thompson', 'jazzie-b'],
    synopsis: 'Claudia Jones created the Carnival as a direct political response to race riots — joy as assertion, not entertainment. Daley Thompson refused to perform gratitude on the Olympic podium — confidence as sovereignty. Jazzie B\'s philosophy: "A happy face, a thumpin\' bass, for a lovin\' race." Three figures who understood that the way you carry yourself is political.',
    duration: '9 min read',
    tags: ['activism', 'carnival', 'sport', 'music', 'resistance']
  }
];

// ============================================
// ERA DATA for timeline browsing
// ============================================

const ERAS = [
  { id: 'victorian', label: 'Victorian', years: 'pre–1900', colour: '#8B6914' },
  { id: 'early-century', label: 'Early Century', years: '1900–1948', colour: '#6B4226' },
  { id: 'windrush', label: 'Windrush', years: '1948–1970', colour: '#1A5276' },
  { id: 'uprising', label: 'Uprising', years: '1970–1985', colour: '#922B21' },
  { id: 'renaissance', label: 'Renaissance', years: '1985–2000', colour: '#1E8449' },
  { id: 'established', label: 'Established', years: '2000–2015', colour: '#7D3C98' },
  { id: 'rising', label: 'Rising', years: '2015–now', colour: '#C8A84B' },
] as const;

// ============================================
// INSTITUTIONAL MARKERS
// Commonwealth Institute, Embassies, Empire Exhibition
// ============================================

interface InstitutionalMarker {
  id: string;
  name: string;
  type: 'high-commission' | 'embassy' | 'cultural-institute' | 'former-colonial' | 'community-institution';
  nation?: string;
  address: string;
  borough: string;
  tubeStation: string;
  tubeColour: string;
  established: number;
  currentStatus: 'active' | 'converted' | 'closed' | 'repurposed';
  significance: string;
  communityConnection: string;
  wembleyDistance: string;
  theGap?: string;
}

const INSTITUTIONAL_MARKERS: InstitutionalMarker[] = [
  {
    id: 'commonwealth-institute',
    name: 'Commonwealth Institute (now Design Museum)',
    type: 'former-colonial',
    address: 'Kensington High Street, W8',
    borough: 'Kensington & Chelsea',
    tubeStation: 'High Street Kensington',
    tubeColour: '#007229',
    established: 1962,
    currentStatus: 'repurposed',
    significance: 'Opened 1962 to celebrate newly independent Commonwealth nations. Each country had its own exhibition space. Closed 2002. Reopened 2016 as the Design Museum — the Commonwealth content gone entirely.',
    communityConnection: 'Built to represent the nations whose citizens came to Britain on the Windrush. Converted without community consultation.',
    wembleyDistance: '20 min via District/Metropolitan line',
    theGap: 'A building built with public money to represent 50+ nations was repurposed into a design museum. No community consultation. The institutional representation of the Caribbean and West African diaspora — gone.'
  },
  {
    id: 'empire-exhibition-wembley',
    name: '1924 British Empire Exhibition Site',
    type: 'former-colonial',
    address: 'Wembley Park, HA9',
    borough: 'Brent',
    tubeStation: 'Wembley Park',
    tubeColour: '#A0A5A9',
    established: 1924,
    currentStatus: 'repurposed',
    significance: 'The British Empire Exhibition of 1924 shaped the entire Wembley landscape. The stadium, the park, the tube infrastructure — all built for an exhibition celebrating the Empire at its peak. The communities now living here are the descendants of the people the exhibition celebrated as imperial subjects.',
    communityConnection: 'The ground under the High Road was shaped by an exhibition of imperial power. Wembley Wonders operates on this land.',
    wembleyDistance: 'This IS Wembley',
    theGap: 'No heritage marker on the Wembley Park landscape acknowledges the communities whose labour and subjection made the 1924 exhibition possible.'
  },
  {
    id: 'jamaican-high-commission',
    name: 'Jamaican High Commission',
    type: 'high-commission',
    nation: 'Jamaica',
    address: '1-2 Prince Consort Road, SW7',
    borough: 'Kensington & Chelsea',
    tubeStation: 'South Kensington',
    tubeColour: '#DC241F',
    established: 1962,
    currentStatus: 'active',
    significance: 'Jamaica gained independence in 1962. The High Commission in Kensington represents the nation whose citizens were the core of the Windrush generation — and whose descendants form a significant part of the Wembley community.',
    communityConnection: 'Jamaican community in Wembley and NW London is among the largest Caribbean communities in Britain.',
    wembleyDistance: '35 min via Jubilee line to Westminster, change',
    theGap: 'The High Commission sits in one of London\'s most expensive postcodes. The community it represents lives largely in zones 3–5. The distance is not just geographic.'
  },
  {
    id: 'ghanaian-high-commission',
    name: 'Ghana High Commission',
    type: 'high-commission',
    nation: 'Ghana',
    address: '13 Belgrave Square, SW1',
    borough: 'Westminster',
    tubeStation: 'Hyde Park Corner',
    tubeColour: '#DC241F',
    established: 1957,
    currentStatus: 'active',
    significance: 'Ghana was the first sub-Saharan African nation to gain independence (1957). The High Commission in Belgrave Square represents the nation of Kanya King\'s father — the Kilburn-born founder of MOBO.',
    communityConnection: 'Kanya King — Ghanaian-Irish, born in Kilburn. Michaela Coel — Ghanaian-British, born in Tower Hamlets. The Ghanaian diaspora is central to Black British cultural output.',
    wembleyDistance: '40 min via Jubilee line',
    theGap: 'Belgrave Square is among the most expensive addresses in London. The Ghanaian community in Britain is concentrated in Peckham, Harlesden, Wembley.'
  },
  {
    id: 'trinidad-high-commission',
    name: 'Trinidad & Tobago High Commission',
    type: 'high-commission',
    nation: 'Trinidad and Tobago',
    address: '42 Belgrave Square, SW1',
    borough: 'Westminster',
    tubeStation: 'Hyde Park Corner',
    tubeColour: '#DC241F',
    established: 1962,
    currentStatus: 'active',
    significance: 'Trinidad and Tobago gained independence in 1962. Claudia Jones — founder of the Notting Hill Carnival and the West Indian Gazette — was Trinidadian. The calypso and carnival tradition that became Europe\'s largest street festival originated here.',
    communityConnection: 'Claudia Jones. The Carnival. The West Indian Gazette. The entire tradition of Black British community celebration traces to Trinidad.',
    wembleyDistance: '40 min via Jubilee line',
    theGap: 'Claudia Jones has a small blue plaque in Notting Hill. The St Pancras Town Hall where she held the first Carnival has no marker. The High Commission that represents her nation is in Belgrave Square.'
  },
  {
    id: 'south-africa-house',
    name: 'South Africa House',
    type: 'embassy',
    nation: 'South Africa',
    address: 'Trafalgar Square, WC2',
    borough: 'Westminster',
    tubeStation: 'Charing Cross',
    tubeColour: '#DC241F',
    established: 1933,
    currentStatus: 'active',
    significance: 'During the apartheid era, South Africa House in Trafalgar Square was a sustained site of anti-apartheid protest — including by Black British activists. The picket ran continuously from 1986 to 1990. Nelson Mandela\'s release was announced to protesters gathered here.',
    communityConnection: 'Black British activism against apartheid was a formative political experience for a generation of community organisers — many of whom are now in their 60s and 70s, in communities like Wembley.',
    wembleyDistance: '45 min via Jubilee line',
  },
  {
    id: 'nigeria-high-commission',
    name: 'Nigeria High Commission',
    type: 'high-commission',
    nation: 'Nigeria',
    address: '9 Northumberland Avenue, WC2',
    borough: 'Westminster',
    tubeStation: 'Embankment',
    tubeColour: '#DC241F',
    established: 1960,
    currentStatus: 'active',
    significance: 'Nigeria gained independence in 1960. The Nigerian diaspora in Britain is one of the largest and most culturally significant — from Sade to Skepta to Wizkid. Daley Thompson\'s father was Nigerian.',
    communityConnection: 'Daley Thompson — Nigerian-Scottish, born Notting Hill. The Nigerian diaspora has shaped British music, sport, and culture disproportionately.',
    wembleyDistance: '40 min via Jubilee line'
  }
];

// ============================================
// QUESTION GATEWAY DATA
// ============================================

const BIG_QUESTIONS = [
  {
    id: 'q1',
    question: 'Why don\'t we know Arthur Wharton?',
    teaser: 'He was the world\'s first Black professional footballer. He held the world sprint record. He died in an unmarked grave.',
    threadId: 'same-rule-different-arenas',
    profileId: 'arthur-wharton'
  },
  {
    id: 'q2',
    question: 'What happened to the Commonwealth Institute?',
    teaser: 'A building built to represent 50 nations. Converted into a design museum. No community consultation.',
    institutionalId: 'commonwealth-institute'
  },
  {
    id: 'q3',
    question: 'Why did Michaela Coel turn down $1 million?',
    teaser: 'Netflix offered her a million dollars. The condition: they wanted everything. She said no.',
    threadId: 'who-owns-the-culture',
    profileId: 'michaela-coel'
  },
  {
    id: 'q4',
    question: 'Where did the Notting Hill Carnival actually start?',
    teaser: 'Not on a street. Not in summer. Indoors. In winter. At St Pancras Town Hall. In 1959.',
    threadId: 'joy-as-politics',
    profileId: 'claudia-jones'
  },
  {
    id: 'q5',
    question: 'What was on the land before Wembley Stadium?',
    teaser: '1924. The British Empire Exhibition. The same Empire whose subjects\' descendants now live on this land.',
    threadId: 'landscape-under-your-feet',
    institutionalId: 'empire-exhibition-wembley'
  },
  {
    id: 'q6',
    question: 'How far is your nation\'s embassy from where you live?',
    teaser: 'Belgrave Square. Kensington. The institutions that represent your heritage and the communities that live it — mapped.',
    threadId: 'distance-embassy-community'
  }
];

// ============================================
// SUBCOMPONENTS
// ============================================

const ProfileCard: React.FC<{ profile: ExcellenceProfile; compact?: boolean }> = ({ profile, compact }) => (
  <div className={`kc-profile-card ${compact ? 'kc-profile-card--compact' : ''}`}>
    <div className="kc-profile-card__era" data-era={profile.era}>
      {profile.era.replace('-', ' ')}
    </div>
    <h3 className="kc-profile-card__name">{profile.name}</h3>
    <p className="kc-profile-card__field">{profile.primaryField}</p>
    {!compact && (
      <>
        <p className="kc-profile-card__origin">📍 {profile.origin}</p>
        <div className="kc-profile-card__known-for">
          {profile.knownFor.slice(0, 2).map((item, i) => (
            <span key={i} className="kc-profile-card__tag">{item}</span>
          ))}
        </div>
        {profile.theGap && (
          <div className="kc-profile-card__gap">
            <span className="kc-profile-card__gap-label">The gap:</span>
            <span className="kc-profile-card__gap-text">{profile.theGap}</span>
          </div>
        )}
      </>
    )}
    {profile.keyQuotes[0] && (
      <blockquote className="kc-profile-card__quote">
        "{profile.keyQuotes[0].text.slice(0, 100)}{profile.keyQuotes[0].text.length > 100 ? '…' : ''}"
      </blockquote>
    )}
  </div>
);

const ThreadCard: React.FC<{ thread: Thread; onSelect: (id: string) => void }> = ({ thread, onSelect }) => (
  <button className="kc-thread-card" onClick={() => onSelect(thread.id)}>
    <div className="kc-thread-card__question">{thread.question}</div>
    <h3 className="kc-thread-card__title">{thread.title}</h3>
    <p className="kc-thread-card__synopsis">{thread.synopsis.slice(0, 120)}…</p>
    <div className="kc-thread-card__meta">
      <span className="kc-thread-card__duration">⏱ {thread.duration}</span>
      <div className="kc-thread-card__tags">
        {thread.tags.slice(0, 3).map(tag => (
          <span key={tag} className="kc-thread-card__tag">{tag}</span>
        ))}
      </div>
    </div>
  </button>
);

const InstitutionalCard: React.FC<{ marker: InstitutionalMarker }> = ({ marker }) => (
  <div className={`kc-inst-card kc-inst-card--${marker.type}`}>
    <div className="kc-inst-card__type">{marker.type.replace('-', ' ')}</div>
    {marker.nation && <div className="kc-inst-card__nation">{marker.nation}</div>}
    <h3 className="kc-inst-card__name">{marker.name}</h3>
    <div className="kc-inst-card__location">
      <span
        className="kc-inst-card__tube-dot"
        style={{ backgroundColor: marker.tubeColour }}
      />
      {marker.tubeStation} · {marker.borough}
    </div>
    <p className="kc-inst-card__significance">{marker.significance.slice(0, 140)}…</p>
    <div className="kc-inst-card__distance">
      🚇 {marker.wembleyDistance} from Wembley Park
    </div>
    {marker.currentStatus !== 'active' && (
      <div className="kc-inst-card__status" data-status={marker.currentStatus}>
        {marker.currentStatus}
      </div>
    )}
    {marker.theGap && (
      <div className="kc-inst-card__gap">
        <strong>The gap:</strong> {marker.theGap.slice(0, 120)}…
      </div>
    )}
  </div>
);

// Blue Plaque visual component
const BluePlaque: React.FC<{
  name: string;
  dates: string;
  achievement: string;
  location: string;
  isCounterArchive?: boolean;
}> = ({ name, dates, achievement, location, isCounterArchive }) => (
  <div className={`kc-plaque ${isCounterArchive ? 'kc-plaque--counter' : 'kc-plaque--official'}`}>
    <div className="kc-plaque__inner">
      {isCounterArchive && (
        <div className="kc-plaque__archive-mark">Wembley Wonders Counter-Archive</div>
      )}
      <div className="kc-plaque__name">{name}</div>
      <div className="kc-plaque__dates">{dates}</div>
      <div className="kc-plaque__achievement">{achievement}</div>
      <div className="kc-plaque__location">{location}</div>
    </div>
  </div>
);

// ============================================
// MAIN COMPONENT
// ============================================

const HeritagePage: React.FC = () => {
  const [browseMode, setBrowseMode] = useState<BrowseMode>('welcome');
  const [activeThread, setActiveThread] = useState<ActiveThread>(null);
  const [activeEra, setActiveEra] = useState<Era | null>(null);
  const [activeDiscipline, setActiveDiscipline] = useState<Discipline | null>(null);
  const [collaborationMode, setCollaborationMode] = useState('individual');
  const [activeStories, setActiveStories] = useState<any[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [visibleProfiles, setVisibleProfiles] = useState<ExcellenceProfile[]>(
    getPioneersByScore(8)
  );
  const mainRef = useRef<HTMLDivElement>(null);

  const handleStorySubmission = (story: any) => {
    setActiveStories(prev => [
      ...prev,
      { ...story, status: 'under_review', id: Date.now() }
    ]);
  };

  const handleThreadSelect = (threadId: string) => {
    setActiveThread(threadId);
    setBrowseMode('thread');
    mainRef.current?.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleEraSelect = (era: Era) => {
    setActiveEra(era);
    setVisibleProfiles(getProfilesByEra(era));
  };

  const handleDisciplineSelect = (discipline: Discipline) => {
    setActiveDiscipline(discipline);
    setVisibleProfiles(getProfilesByDiscipline(discipline));
  };

  const handleSearch = (query: string) => {
    setSearchQuery(query);
    if (!query.trim()) {
      setVisibleProfiles(getPioneersByScore(8));
      return;
    }
    const q = query.toLowerCase();
    setVisibleProfiles(
      BLACK_BRITISH_EXCELLENCE.filter(p =>
        p.name.toLowerCase().includes(q) ||
        p.primaryField.toLowerCase().includes(q) ||
        p.knownFor.some(k => k.toLowerCase().includes(q)) ||
        p.origin.toLowerCase().includes(q) ||
        p.heritage.some(h => h.toLowerCase().includes(q))
      )
    );
  };

  const currentThread = activeThread
    ? THREADS.find(t => t.id === activeThread)
    : null;

  const threadProfiles = currentThread
    ? currentThread.profileIds
        .map(id => BLACK_BRITISH_EXCELLENCE.find(p => p.id === id))
        .filter(Boolean) as ExcellenceProfile[]
    : [];

  // ============================================
  // RENDER — THREAD VIEW
  // ============================================

  if (browseMode === 'thread' && currentThread) {
    return (
      <div className="kc kc--thread" ref={mainRef}>
        <div className="kc__thread-nav">
          <button
            className="kc__back-btn"
            onClick={() => { setBrowseMode('welcome'); setActiveThread(null); }}
          >
            ← Back to Knowledge Commons
          </button>
          <span className="kc__thread-duration">⏱ {currentThread.duration}</span>
        </div>

        <article className="kc__thread-article">
          <header className="kc__thread-header">
            <div className="kc__thread-question">{currentThread.question}</div>
            <h1 className="kc__thread-title">{currentThread.title}</h1>
            <p className="kc__thread-synopsis">{currentThread.synopsis}</p>
            <div className="kc__thread-tags">
              {currentThread.tags.map(tag => (
                <span key={tag} className="kc__thread-tag">{tag}</span>
              ))}
            </div>
          </header>

          {/* Profile deep dives in thread order */}
          <div className="kc__thread-profiles">
            {threadProfiles.map((profile, i) => (
              <section key={profile.id} className="kc__thread-profile">
                <div className="kc__thread-profile-num">{String(i + 1).padStart(2, '0')}</div>

                <div className="kc__thread-profile-content">
                  <div className="kc__thread-profile-header">
                    <h2>{profile.name}</h2>
                    <span className="kc__thread-profile-field">{profile.primaryField}</span>
                    <span className="kc__thread-profile-era" data-era={profile.era}>
                      {profile.era.replace('-', ' ')}
                    </span>
                  </div>

                  {/* Biography */}
                  {profile.biography.map((section, j) => (
                    <div key={j} className="kc__thread-bio-section">
                      <h3>{section.heading}</h3>
                      <p>{section.content}</p>
                    </div>
                  ))}

                  {/* Timeline */}
                  <div className="kc__thread-timeline">
                    <h3>Timeline</h3>
                    <div className="kc__timeline-strip">
                      {profile.timeline.map((entry, k) => (
                        <div
                          key={k}
                          className="kc__timeline-entry"
                          data-significance={entry.significance}
                        >
                          <span className="kc__timeline-year">{entry.year}</span>
                          <span className="kc__timeline-event">{entry.event}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Geographic pins */}
                  {profile.geographicPins.length > 0 && (
                    <div className="kc__thread-geography">
                      <h3>On the Map</h3>
                      <div className="kc__geography-pins">
                        {profile.geographicPins.map((pin, k) => (
                          <div key={k} className="kc__geography-pin">
                            {pin.tubeStation && (
                              <span
                                className="kc__pin-tube"
                                style={{
                                  backgroundColor:
                                    pin.tubeLine === 'victoria' ? '#009FE0' :
                                    pin.tubeLine === 'jubilee' ? '#A0A5A9' :
                                    pin.tubeLine === 'northern' ? '#231F20' :
                                    pin.tubeLine === 'central' ? '#DC241F' :
                                    pin.tubeLine === 'overground' ? '#EE7C0E' :
                                    pin.tubeLine === 'district' ? '#007229' :
                                    pin.tubeLine === 'bakerloo' ? '#894E24' : '#555'
                                }}
                              >
                                {pin.tubeStation}
                              </span>
                            )}
                            <span className="kc__pin-area">{pin.area}</span>
                            <span className="kc__pin-significance">{pin.significance}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Structural context */}
                  <div className="kc__thread-structural">
                    <h3>The Structural Context</h3>
                    <p>{profile.structuralContext}</p>
                  </div>

                  {/* The Gap */}
                  {profile.theGap && (
                    <div className="kc__thread-gap">
                      <h3>The Gap</h3>
                      <p>{profile.theGap}</p>
                    </div>
                  )}

                  {/* Counter-archive plaque */}
                  {profile.geographicPins[0] && (
                    <div className="kc__thread-plaque">
                      <h3>The Plaque That Should Exist</h3>
                      <BluePlaque
                        name={profile.name.toUpperCase()}
                        dates={`${profile.birthYear || ''}${profile.deathYear ? `–${profile.deathYear}` : ''}`}
                        achievement={profile.primaryField}
                        location={profile.geographicPins[0].area}
                        isCounterArchive={true}
                      />
                    </div>
                  )}

                  {/* Lesson / debate prompt */}
                  {profile.lessonsWeLearn[0] && (
                    <div className="kc__thread-lesson">
                      <h3>Take This Further</h3>
                      <div className="kc__lesson-card">
                        <div className="kc__lesson-title">{profile.lessonsWeLearn[0].title}</div>
                        <div className="kc__lesson-overview">{profile.lessonsWeLearn[0].overview}</div>
                        {profile.lessonsWeLearn[0].debatePrompt && (
                          <div className="kc__lesson-debate">
                            <span className="kc__lesson-debate-label">🎙 Debate:</span>
                            {profile.lessonsWeLearn[0].debatePrompt}
                          </div>
                        )}
                        <div className="kc__lesson-takeaways">
                          {profile.lessonsWeLearn[0].keyTakeaways.map((t, k) => (
                            <div key={k} className="kc__lesson-takeaway">✓ {t}</div>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </section>
            ))}
          </div>

          {/* Thread conclusion */}
          <footer className="kc__thread-footer">
            <div className="kc__thread-footer-question">
              Returning to the question: <em>{currentThread.question}</em>
            </div>
            <div className="kc__thread-cta">
              <p>This thread is part of the Wembley Wonders Knowledge Commons — a living counter-archive assembled by and for the community.</p>
              <div className="kc__thread-cta-buttons">
                <button
                  className="kc__btn kc__btn--primary"
                  onClick={() => { setBrowseMode('contribute'); }}
                >
                  Add to This Archive
                </button>
                <button
                  className="kc__btn kc__btn--secondary"
                  onClick={() => setBrowseMode('welcome')}
                >
                  Explore More Threads
                </button>
              </div>
            </div>
          </footer>
        </article>
      </div>
    );
  }

  // ============================================
  // RENDER — MAIN KNOWLEDGE COMMONS
  // ============================================

  return (
    <div className="kc" ref={mainRef}>

      {/* ── HERO ── */}
      <header className="kc__hero">
        <div className="kc__hero-texture" />
        <div className="kc__hero-content">
          <div className="kc__hero-kicker">Wembley Wonders Knowledge Commons</div>
          <h1 className="kc__hero-title">
            The History<br />
            <em>They Didn't Teach You</em>
          </h1>
          <p className="kc__hero-sub">
            A counter-archive of Black British excellence, London's institutional
            geography, and the cultural lineages that run under the city's surface.
            Public. Free. Growing.
          </p>
          <div className="kc__hero-stats">
            <div className="kc__hero-stat">
              <span className="kc__hero-stat-num">{BLACK_BRITISH_EXCELLENCE.length}</span>
              <span className="kc__hero-stat-label">Pioneer profiles</span>
            </div>
            <div className="kc__hero-stat">
              <span className="kc__hero-stat-num">{THREADS.length}</span>
              <span className="kc__hero-stat-label">Deep-dive threads</span>
            </div>
            <div className="kc__hero-stat">
              <span className="kc__hero-stat-num">{INSTITUTIONAL_MARKERS.length}</span>
              <span className="kc__hero-stat-label">Institutional markers</span>
            </div>
            <div className="kc__hero-stat">
              <span className="kc__hero-stat-num">{TIMELINE_GAME_EVENTS.length}</span>
              <span className="kc__hero-stat-label">Timeline events</span>
            </div>
          </div>
        </div>
      </header>

      {/* ── BROWSE MODE SELECTOR ── */}
      <nav className="kc__browse-nav">
        <button
          className={`kc__browse-tab ${browseMode === 'welcome' ? 'active' : ''}`}
          onClick={() => setBrowseMode('welcome')}
        >
          <span className="kc__browse-icon">🗂</span>
          Browse All
        </button>
        <button
          className={`kc__browse-tab ${browseMode === 'thread' ? 'active' : ''}`}
          onClick={() => setBrowseMode('thread')}
        >
          <span className="kc__browse-icon">🧵</span>
          By Thread
        </button>
        <button
          className={`kc__browse-tab ${browseMode === 'place' ? 'active' : ''}`}
          onClick={() => setBrowseMode('place')}
        >
          <span className="kc__browse-icon">🗺</span>
          By Place
        </button>
        <button
          className={`kc__browse-tab ${browseMode === 'era' ? 'active' : ''}`}
          onClick={() => setBrowseMode('era')}
        >
          <span className="kc__browse-icon">📅</span>
          By Era
        </button>
        <button
          className={`kc__browse-tab ${browseMode === 'question' ? 'active' : ''}`}
          onClick={() => setBrowseMode('question')}
        >
          <span className="kc__browse-icon">❓</span>
          By Question
        </button>
        <button
          className={`kc__browse-tab ${browseMode === 'contribute' ? 'active' : ''}`}
          onClick={() => setBrowseMode('contribute')}
        >
          <span className="kc__browse-icon">✍</span>
          Contribute
        </button>
      </nav>

      <main className="kc__main">

        {/* ── WELCOME / BROWSE ALL ── */}
        {(browseMode === 'welcome') && (
          <>
            {/* Question Gateway — the most inviting entry point */}
            <section className="kc__section kc__section--questions">
              <div className="kc__section-header">
                <h2>Start with a Question</h2>
                <p>The archive is structured around things that should be better known.</p>
              </div>
              <div className="kc__questions-grid">
                {BIG_QUESTIONS.map(q => (
                  <button
                    key={q.id}
                    className="kc__question-card"
                    onClick={() => q.threadId && handleThreadSelect(q.threadId)}
                  >
                    <div className="kc__question-text">{q.question}</div>
                    <div className="kc__question-teaser">{q.teaser}</div>
                    <span className="kc__question-arrow">Read the thread →</span>
                  </button>
                ))}
              </div>
            </section>

            {/* Pioneer profiles */}
            <section className="kc__section kc__section--profiles">
              <div className="kc__section-header">
                <h2>The Pioneers</h2>
                <p>Profiles scored by cultural impact and historical significance.</p>
                <div className="kc__search">
                  <input
                    type="text"
                    placeholder="Search by name, field, origin, heritage…"
                    value={searchQuery}
                    onChange={e => handleSearch(e.target.value)}
                    className="kc__search-input"
                  />
                </div>
                <div className="kc__discipline-filter">
                  {(['sport', 'music', 'entrepreneurship', 'arts', 'activism', 'science-tech'] as Discipline[]).map(d => (
                    <button
                      key={d}
                      className={`kc__filter-btn ${activeDiscipline === d ? 'active' : ''}`}
                      onClick={() => handleDisciplineSelect(d)}
                    >
                      {d.replace('-', ' ')}
                    </button>
                  ))}
                  <button
                    className="kc__filter-btn"
                    onClick={() => { setActiveDiscipline(null); setVisibleProfiles(getPioneersByScore(8)); }}
                  >
                    all
                  </button>
                </div>
              </div>
              <div className="kc__profiles-grid">
                {visibleProfiles.map(profile => (
                  <ProfileCard key={profile.id} profile={profile} />
                ))}
              </div>
            </section>

            {/* Threads preview */}
            <section className="kc__section kc__section--threads">
              <div className="kc__section-header">
                <h2>Deep-Dive Threads</h2>
                <p>Structured narratives connecting multiple figures, places, and eras around a single question.</p>
              </div>
              <div className="kc__threads-grid">
                {THREADS.map(thread => (
                  <ThreadCard key={thread.id} thread={thread} onSelect={handleThreadSelect} />
                ))}
              </div>
            </section>

            {/* Counter-archive plaques preview */}
            <section className="kc__section kc__section--plaques">
              <div className="kc__section-header">
                <h2>The Missing Plaques</h2>
                <p>
                  English Heritage has issued 950+ blue plaques in London.
                  Here are figures who arguably deserve one more than many who have one.
                </p>
              </div>
              <div className="kc__plaques-row">
                {getPioneersByScore(9).slice(0, 4).map(profile => (
                  <BluePlaque
                    key={profile.id}
                    name={profile.name.toUpperCase()}
                    dates={`${profile.birthYear || ''}${profile.deathYear ? `–${profile.deathYear}` : '–'}`}
                    achievement={profile.primaryField}
                    location={profile.geographicPins[0]?.area || 'London'}
                    isCounterArchive={true}
                  />
                ))}
              </div>
              <div className="kc__plaques-cta">
                <button
                  className="kc__btn kc__btn--secondary"
                  onClick={() => setBrowseMode('contribute')}
                >
                  Add a Missing Plaque
                </button>
              </div>
            </section>
          </>
        )}

        {/* ── BY THREAD ── */}
        {browseMode === 'thread' && !activeThread && (
          <section className="kc__section">
            <div className="kc__section-header">
              <h2>Deep-Dive Threads</h2>
              <p>Each thread follows a single question across multiple figures, places, and eras. 8–15 minutes each.</p>
            </div>
            <div className="kc__threads-grid kc__threads-grid--full">
              {THREADS.map(thread => (
                <ThreadCard key={thread.id} thread={thread} onSelect={handleThreadSelect} />
              ))}
            </div>
          </section>
        )}

        {/* ── BY PLACE ── */}
        {browseMode === 'place' && (
          <section className="kc__section">
            <div className="kc__section-header">
              <h2>By Place</h2>
              <p>London's tube network as a map of Black British history. Each stop carries a story.</p>
            </div>

            {/* Route stops */}
            <div className="kc__place-routes">
              <h3>Tube Stops with Stories</h3>
              <div className="kc__routes-list">
                {LONDON_ROUTES.map((stop, i) => {
                  const profiles = stop.profiles
                    .map(id => BLACK_BRITISH_EXCELLENCE.find(p => p.id === id))
                    .filter(Boolean) as ExcellenceProfile[];
                  return (
                    <div key={i} className="kc__route-stop">
                      <div className="kc__route-stop-header">
                        {stop.tubeLine && (
                          <span
                            className="kc__route-tube-dot"
                            style={{
                              backgroundColor:
                                stop.tubeLine === 'victoria' ? '#009FE0' :
                                stop.tubeLine === 'jubilee' ? '#A0A5A9' :
                                stop.tubeLine === 'northern' ? '#231F20' :
                                stop.tubeLine === 'central' ? '#DC241F' :
                                stop.tubeLine === 'overground' ? '#EE7C0E' :
                                stop.tubeLine === 'district' ? '#007229' :
                                stop.tubeLine === 'bakerloo' ? '#894E24' : '#555'
                            }}
                          />
                        )}
                        <span className="kc__route-station">{stop.tubeStation || stop.area}</span>
                        <span className="kc__route-area">{stop.area}</span>
                        <span className="kc__route-era" data-era={stop.era}>{stop.era}</span>
                      </div>
                      <p className="kc__route-significance">{stop.significance}</p>
                      {profiles.length > 0 && (
                        <div className="kc__route-profiles">
                          {profiles.map(p => (
                            <span key={p.id} className="kc__route-profile-tag">{p.name}</span>
                          ))}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Institutional markers */}
            <div className="kc__place-institutions">
              <h3>Institutions, Embassies & High Commissions</h3>
              <p className="kc__place-intro">
                The formal institutional geography of the post-colonial world,
                written in London's bricks and mortar.
              </p>
              <div className="kc__inst-grid">
                {INSTITUTIONAL_MARKERS.map(marker => (
                  <InstitutionalCard key={marker.id} marker={marker} />
                ))}
              </div>
            </div>
          </section>
        )}

        {/* ── BY ERA ── */}
        {browseMode === 'era' && (
          <section className="kc__section">
            <div className="kc__section-header">
              <h2>By Era</h2>
              <p>Select a period to see who was active and what was happening simultaneously.</p>
            </div>
            <div className="kc__era-selector">
              {ERAS.map(era => (
                <button
                  key={era.id}
                  className={`kc__era-btn ${activeEra === era.id ? 'active' : ''}`}
                  style={{ borderColor: era.colour }}
                  onClick={() => handleEraSelect(era.id as Era)}
                >
                  <span className="kc__era-dot" style={{ backgroundColor: era.colour }} />
                  <span className="kc__era-label">{era.label}</span>
                  <span className="kc__era-years">{era.years}</span>
                </button>
              ))}
            </div>

            {activeEra && (
              <>
                <div className="kc__era-timeline">
                  <h3>What Was Happening</h3>
                  <div className="kc__timeline-events">
                    {TIMELINE_GAME_EVENTS
                      .filter(e => {
                        const eraData = ERAS.find(er => er.id === activeEra);
                        return true; // Would filter by year range — extend as needed
                      })
                      .slice(0, 6)
                      .map(event => (
                        <div key={event.id} className="kc__timeline-event" data-category={event.category}>
                          <span className="kc__timeline-event-year">{event.year}</span>
                          <span className="kc__timeline-event-desc">{event.description}</span>
                          <span className="kc__timeline-event-cat">{event.category}</span>
                        </div>
                      ))
                    }
                  </div>
                </div>
                <div className="kc__era-profiles">
                  <h3>Figures of This Era</h3>
                  <div className="kc__profiles-grid">
                    {visibleProfiles.map(profile => (
                      <ProfileCard key={profile.id} profile={profile} compact />
                    ))}
                  </div>
                </div>
              </>
            )}
          </section>
        )}

        {/* ── BY QUESTION ── */}
        {browseMode === 'question' && (
          <section className="kc__section">
            <div className="kc__section-header">
              <h2>Start with a Question</h2>
              <p>The most powerful entry point for people who don't yet know what they're looking for.</p>
            </div>
            <div className="kc__questions-grid kc__questions-grid--full">
              {BIG_QUESTIONS.map(q => (
                <button
                  key={q.id}
                  className="kc__question-card kc__question-card--large"
                  onClick={() => q.threadId && handleThreadSelect(q.threadId)}
                >
                  <div className="kc__question-text">{q.question}</div>
                  <div className="kc__question-teaser">{q.teaser}</div>
                  <span className="kc__question-arrow">Read the thread →</span>
                </button>
              ))}
            </div>
          </section>
        )}

        {/* ── CONTRIBUTE ── */}
        {browseMode === 'contribute' && (
          <section className="kc__section kc__section--contribute">
            <div className="kc__section-header">
              <h2>Contribute to the Archive</h2>
              <p>
                The knowledge commons grows through community contribution.
                Add a pioneer profile. Submit a missing plaque nomination.
                Share an oral history. Connect a story to the map.
              </p>
            </div>

            <div className="kc__contribute-modes">
              <button
                className={`kc__contribute-mode ${collaborationMode === 'individual' ? 'active' : ''}`}
                onClick={() => setCollaborationMode('individual')}
              >
                <span>👤</span>
                <strong>Individual Contribution</strong>
                <p>Submit a story, pioneer profile, or missing plaque nomination</p>
              </button>
              <button
                className={`kc__contribute-mode ${collaborationMode === 'collaborative' ? 'active' : ''}`}
                onClick={() => setCollaborationMode('collaborative')}
              >
                <span>👥</span>
                <strong>Community Workshop</strong>
                <p>Join a guided heritage research session</p>
              </button>
            </div>

            {collaborationMode === 'individual' && (
              <div className="kc__contribute-form">
                <div className="kc__contribute-guidance">
                  <h3>How contributions work</h3>
                  <div className="kc__workflow">
                    <div className="kc__workflow-step">
                      <span className="kc__workflow-num">01</span>
                      <div>
                        <strong>You submit</strong>
                        <p>A pioneer profile, a missing plaque nomination, an oral history, or a routes connection.</p>
                      </div>
                    </div>
                    <div className="kc__workflow-step">
                      <span className="kc__workflow-num">02</span>
                      <div>
                        <strong>Maya reviews</strong>
                        <p>Cultural sensitivity guidance and factual cross-referencing.</p>
                      </div>
                    </div>
                    <div className="kc__workflow-step">
                      <span className="kc__workflow-num">03</span>
                      <div>
                        <strong>Community validates</strong>
                        <p>Other contributors can verify, add context, or connect to existing profiles.</p>
                      </div>
                    </div>
                    <div className="kc__workflow-step">
                      <span className="kc__workflow-num">04</span>
                      <div>
                        <strong>Archive grows</strong>
                        <p>Published to the knowledge commons. Credited to you. Permanently accessible.</p>
                      </div>
                    </div>
                  </div>
                </div>
                <StoryForm onSubmit={handleStorySubmission} />
              </div>
            )}

            {collaborationMode === 'collaborative' && (
              <div className="kc__workshop">
                <h3>Heritage Research Workshop</h3>
                <p>
                  Facilitated sessions combining community knowledge, practical research skills,
                  and Maya's cultural guidance. Open to all — member and non-member.
                </p>
                <div className="kc__workshop-features">
                  <div className="kc__workshop-feature">
                    <strong>Skills sharing</strong>
                    <p>Learn research, archival, and oral history techniques</p>
                  </div>
                  <div className="kc__workshop-feature">
                    <strong>Resource access</strong>
                    <p>British Library resources, borough archive connections, oral history equipment</p>
                  </div>
                  <div className="kc__workshop-feature">
                    <strong>Community review</strong>
                    <p>Peer accuracy checking and contextual enrichment</p>
                  </div>
                </div>
                <button className="kc__btn kc__btn--primary">Join Next Workshop Session</button>
              </div>
            )}

            {/* Active submissions */}
            {activeStories.length > 0 && (
              <div className="kc__active-submissions">
                <h3>Submissions Under Review</h3>
                <div className="kc__submissions-list">
                  {activeStories.map((story: any) => (
                    <div key={story.id} className="kc__submission">
                      <span className="kc__submission-title">{story.title}</span>
                      <span className="kc__submission-status">{story.status}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </section>
        )}

      </main>

      {/* ── FOOTER STRIP ── */}
      <footer className="kc__footer">
        <div className="kc__footer-content">
          <p className="kc__footer-statement">
            This archive is assembled by Wembley Wonders CIC and the communities it serves.
            It is a counter-institution — built because the official record is incomplete.
          </p>
          <div className="kc__footer-links">
            <Link to="/programmes/pageturners">Pageturners — Research & Writing</Link>
            <Link to="/programmes/gtechcasters">G-Tech Casters — Debate & Broadcast</Link>
            <Link to="/programmes/trubble-n-bass">Trubble n Bass — Sound Lineage</Link>
            <Link to="/oral-history">Full Oral History Archive</Link>
          </div>
        </div>
      </footer>

      {/* Maya cultural guidance — retained from original */}
      <MayaCrisisIntegration
        currentLanguage="en"
        crisisLevel="normal"
        userCommunity="wembley-central"
      />

    </div>
  );
};

export default HeritagePage;